name: Deploy gate test
on:
  push:
    branches: [main, develop, staging, deploy-slack-message-test-branch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "gate test"
