name: Deploy gate test
on:
  push:
    branches: [main, develop, staging, little-fixes-to-sunshine]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "gate test"
